#!/bin/bash

old_file=${1}
new_file=""
target_file=""

if [ -f ${old_file} ];then
	echo ${old_file} | grep "\.bc$" &> /dev/null;
	if [ ! $? -eq 0 ];then
		echo "add .bc suffix";
		mv ${old_file} ${old_file}.bc
		new_file=${old_file}.bc
		target_file=${old_file}
	else
		new_file=${old_file}
		target_file=`echo ${old_file} | sed "s:\.bc$::g"`
	fi
	src_file=`cat resource-rel`
	echo emcc ${new_file} -o ${target_file}.html `for file in ${src_file};do echo --preload-file ${file} " ";done` "\n" &> /tmp/emcc.log
	echo "compile command is save in /tmp/emcc.log"
	emcc -O1 ${new_file} -o index.html `for file in ${src_file};do echo --preload-file ${file} " ";done`
else
	echo "${old_file} dose not exists" 
	echo "usage: compile_to_html filename"
fi
